name: Build and deploy docs
on:
    push:
        branches:
            - main
        paths:
            - "**.js"
            - "**.ts"

permissions:
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        name: Build docs
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Cache Node.js dependencies
              uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Install Node.js dependencies
              run: yarn install --immutable

            - name: Build docs
              run: yarn docs

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: docs/

    deploy:
        name: Deploy docs
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
