name: Lint and test

on:
    push:
        paths:
            - "**.js"
            - "**.ts"
    pull_request:
        paths:
            - "**.js"
            - "**.ts"

jobs:
    run-linters-and-tests:
        name: Run linters and tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Cache Node.js dependencies
              uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Node.js dependencies
              run: yarn install --immutable

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  continue_on_error: false
                  eslint: true
                  eslint_extensions: js,ts
                  prettier: true

            - name: Run tests
              run: yarn testCoverage

            - name: Report test coverage to DeepSource
              run: |
                  curl https://deepsource.io/cli | sh

                  ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
              env:
                  DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
