name: Lint and test

on:
    push:
    pull_request:

jobs:
    run-linters-and-tests:
        name: Run linters and tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Cache Node.js dependencies
              uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: "pnpm"

            - name: Install Node.js dependencies
              run: pnpm install --frozen-lockfile

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  continue_on_error: false
                  eslint: true
                  eslint_extensions: js,ts
                  prettier: true

            - name: Run tests
              run: pnpm testCoverage

            - name: Report test coverage to DeepSource
              run: |
                  curl https://deepsource.io/cli | sh

                  ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
              env:
                  DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
